### ISSUE TITLE
When using uio_irqwait_timeout only one read is performed

### ISSUE THREAD

**Issue by T721** [Linutronix/libuio#9]
Hi @Linutronix,

i'm currently experimenting with the libuio.
I tried to use the uio_irqwait_timeout() following an example i got from Linutronix.

I experienced, that this method reads once after data is ready.
After that read, the timeout runs and is never resetted and does not wait anymore.
If I implement the function of uio_irqwait_timeout myself and remove the read(),
then the read out works but the select does not wait anymore if the fd gets ready but polls it as fast as processor can handle it.

I really want to catch hardware interrupts in my users code.
Can you please help me to find where i am wrong?

I created a new uionode in my devicetree called bmi160.
Im using this example:
```

    struct uio_info_t *info;
    int ret;

    info = uio_find_by_uio_name ("bmi160");
    if (!info)
    {
            printf ("lf112 device not found\n");
            return 1;
    }

    ret = uio_open (info);
    if (ret)
    {
            printf ("uio_open failed\n");
            return 1;
    }

    ret = uio_enable_irq (info);
    if (ret)
    {
            printf ("failed to enable uio interrupt\n");
            return 1;
    }

int32_t retwait = uio_irqwait_timeout (info, &timeout); //this only reads once, then always returns timeout

...
```

when i go with my implementation i use the following

```
        //std::cout << select(fd + 1, &readfds, nullptr, nullptr, &timeout) << std::endl;
       // retwait = read (fd, &dummy, 4);

        //select(fd + 1, &readfds, nullptr, nullptr, &timeout);

        if (retwait >= 0)//FD_ISSET(fd, &readfds))
        {
```

**Comment by manut** [comment]
please provide the initialization of the timeout variable.

**Comment by manut** [comment]
i don't think this is a libuio bug. Seems to be a problem of your usage. Initialization, loop, etc.

Can't be resolved here, because code postings are incomplete.
